name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus
        with:
          project: "COSC 310 Project: ART"
          column: "In Progress"
          repo-token: ART
